### ISSUE TITLE
structurepage fallpage to current page

### ISSUE THREAD

**Issue by jenstornell** [CalebGrove/select-a-structure#7]
I was surpriced that I needed to add `structurepage` to my blueprint. It's not very flexible if I want to use the blueprint for more than one page and I want the structure field on the same page.

My suggestion, fallback to the current page if `structurepage` is missing.

**Comment by calebgrove** [comment]
@jenstornell I fully agree. When I get around to #6, I'll implement this.

**Comment by colourmafia** [comment]
I agree! Any idea of when this may be done? Great plugin otherwise, but this stops me from being able to use it!

**Comment by calebgrove** [comment]
Thanks @colourmafia. I'll try to get a small update out this weekend with this change.

**Comment by colourmafia** [comment]
Just saw this - will keep my eyes peeled!

**Comment by calebgrove** [comment]
Alright, as of v1.2.0, if `structurepage` either doesn't exist in the blueprint, or is left valueless (blank), we will fall back to using the current page. :)

**Comment by colourmafia** [comment]
Thanks so much @calebgrove - tested and working perfectly. Lifesaver!
